# Generated by Django 6.0.3 on 2026-04-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somali', models.CharField(max_length=500)),
                ('english', models.CharField(max_length=500)),
                ('audio_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_notes', to='curriculum.phrase')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('recognition', 'Recognition'), ('recall', 'Recall'), ('production', 'Production')], db_index=True, max_length=20)),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('distractor_1', models.CharField(max_length=500)),
                ('distractor_2', models.CharField(max_length=500)),
                ('distractor_3', models.CharField(max_length=500)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='curriculum.phrase')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category_tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('xp_reward', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('unlock_requires', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_by', to='curriculum.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='curriculum.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='phrase',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='curriculum.subtopic'),
        ),
        migrations.CreateModel(
            name='KeyPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somali_pattern', models.CharField(max_length=200)),
                ('english_pattern', models.CharField(max_length=200)),
                ('breakdown', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_patterns', to='curriculum.subtopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CommonMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong', models.CharField(max_length=300)),
                ('correct', models.CharField(max_length=300)),
                ('explanation', models.TextField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_mistakes', to='curriculum.subtopic')),
            ],
        ),
        migrations.CreateModel(
            name='SurvivalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somali', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survival_lines', to='curriculum.subtopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
