# Generated by Django 6.0.3 on 2026-05-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='is_discoverable',
            field=models.BooleanField(default=False),
        ),
    ]
