# Generated by Django 6.0.3 on 2026-04-30 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_given', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='curriculum.quizquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('subtopics_completed', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_progress', to='curriculum.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'section')},
            },
        ),
        migrations.CreateModel(
            name='UserSubtopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrases_completed', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('current_step', models.CharField(choices=[('template', 'Template'), ('practice', 'Practice'), ('quiz', 'Quiz'), ('review', 'Review')], default='template', max_length=20)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_progress', to='curriculum.subtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subtopic')},
            },
        ),
        migrations.CreateModel(
            name='VocabReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review', models.DateTimeField(db_index=True)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocab_reviews', to='curriculum.phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phrase')},
            },
        ),
    ]
