# Generated by Django 6.0.3 on 2026-05-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubtopicprogress',
            name='current_step',
            field=models.CharField(choices=[('flashcard', 'Flashcard'), ('quiz', 'Quiz'), ('done', 'Done')], default='flashcard', max_length=20),
        ),
    ]
