# Generated by Django 6.0.3 on 2026-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storyline',
            name='timestamp_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storyline',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
