# Generated by Django 6.0.3 on 2026-05-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_story_audio_url_storyline_timestamp_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('distractor_1', models.CharField(max_length=500)),
                ('distractor_2', models.CharField(max_length=500)),
                ('distractor_3', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='content.story')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
